status_led:
  pin:
    number: D4
    inverted: True

esphome:
  name: deep-sleep
  platform: ESP32
  board: wemos_d1_mini32
  on_boot:
    then:
      - deep_sleep.prevent: deep_sleep_1

<<: !include base.yaml

deep_sleep:
  id: deep_sleep_1
  run_duration: 30s
  sleep_duration: 10min

mqtt:
  id: mqtt_client
  broker: 192.168.1.23
  discovery: True
  on_message:
    - topic: esp/test
      then:
        - logger.log: Got ESP test message
    - topic: esp/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: esp/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1
