esphome:
  name: notifier-button-living-room
  platform: ESP8266
  board: esp12e

<<: !include base.yaml

binary_sensor:
  - platform: gpio
    pin: GPIO15
    name: "Notifier Button Living Room 0"
    icon: "mdi:gesture-tap-button"
