esphome:
  name: notifier-button-bedroom
  platform: ESP32
  #board: wemos_d1_mini32
  board: wemos_d1_mini32

<<: !include base.yaml

binary_sensor:
  - platform: gpio
    pin: GPIO26
    name: "Notifier Button Bedroom"
    icon: "mdi:gesture-tap-button"
