esphome:
  name: notifier-button-bedroom
  platform: ESP8266
  board: esp12e

<<: !include base.yaml

binary_sensor:
  - platform: gpio
    pin: GPIO15
    name: "Notifier Button Bedroom"
    icon: "mdi:gesture-tap-button"
