# Example configuration entry
status_led:
  pin:
    number: GPIO5
    inverted: True

esphome:
  name: status-light
  platform: ESP32
  # board: wemos_d1_mini32
  board: lolin32

<<: !include base.yaml

light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO23
    num_leds: 16
    rgb_order: GRB
    name: "Status Light RGB Ring"

switch:
  - platform: gpio
    pin: 25
    id: button0
    name: "Status Button 0"
    icon: "mdi:gate"
    on_turn_on:
      - delay: 250ms
      - switch.turn_off: button0
