# Example configuration entry
status_led:
  pin:
    number: GPIO5
    inverted: True

esphome:
  name: status-light
  platform: ESP32
  # board: wemos_d1_mini32
  board: lolin32

<<: !include base.yaml

light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO23
    num_leds: 16
    rgb_order: GRB
    name: "Status Light RGB Ring 0"
  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO21
    num_leds: 16
    rgb_order: GRB
    name: "Status Light RGB Ring 1"

binary_sensor:
  - platform: gpio
    pin: 25
    name: "Status Button 0"
    icon: "mdi:gesture-tap-button"
  - platform: gpio
    pin: 26
    name: "Status Button 1"
    icon: "mdi:gesture-tap-button"

# switch:
#   - platform: gpio
#     pin: 25
#     id: button0
#     name: "Status Button 0"
#     icon: "mdi:gate"
#     on_turn_on:
#       - delay: 250ms
#       - switch.turn_off: button0
